opam-version: "2.0"
name: "refinedcc-builddep"
version: "dev"
synopsis: "dependencies for RefinedCC"
description: ""
authors: [ "William Mansky" 
]
maintainer: "William Mansky"
homepage: "https://github.com/UIC-verif-group/compcert-mod/"

depends: [
  "cmdliner" {>= "1.1.0"}
  "earley" {= "3.0.0"}
  "toml" {>= "6.0.0"}
  "ubase" {>= "0.04"}
]
